### ISSUE TITLE
Rails 3.2

### ISSUE THREAD

**Issue by borisrorsvort** [jongilbraith/simple-private-messages#21]
Rails 3.2 starts to deprecate vendor/plugins and rails 4 will delete them. 
Do you have any plan soon to convert this plugin into a gem or at least make a proper initializer generator to move it to lib/ ?

**Comment by safarista** [comment]
Hi @borisrorsvort I think a gem is better due to dependency issues. If you have sometime do one and send me a pull request. Am swamped at the moment for the next coming weeks.

When I find time I will try make the gem + tag for >= Rails 3.2 *

Meanwhile if you find time you could create the generators to move it to the /lib then send me a pull request.
